name: TC ASA Build and Test

on: [push]

jobs:
  build-backend:
    name: Build & Test TC ASA
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pipenv
      run: python -m pip install --upgrade pipenv==2022.10.25 wheel

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.9
        cache: "pipenv"
        cache-dependency-path: "**/Pipfile.lock"

    - name: Install dependencies
      run: |
        pipenv install --deploy --dev

    - uses: pre-commit/action@v3.0.0
      name: "Linters and formatters check"
      with:
        extra_args: --all-files

    - name: Run Algorand sandbox
      run: docker run -d -p 4001:4001 -p 4002:4002 makerxau/algorand-sandbox-dev

    - name: Sleep to allow the sandbox to start
      run: sleep 10

    - name: Run pytest
      run: pipenv run pytest
